name: desktop

on:
  push:
    branches: [desktop-release]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/build-desktop
        with:
          target: aarch64-apple-darwin
          publish: 'false'
